// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htbupygpcptvwixyxhog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0YnVweWdwY3B0dndpeHl4aG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTI2MzQsImV4cCI6MjA1OTk2ODYzNH0.YIos25frq3ZtGTYA7_pYCkV1Zywg7ieYlQjzj1pgra8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);